### PR TITLE
Fixed namespaces with starting slash

### LINKED ISSUE #42: Namespace \yii\base was not found in the file …/vendor/yiisoft/yii2/base/Application.php
I got error
  [Go\ParserReflection\ReflectionException]                                                             
  Namespace \yii\base was not found in the file …/vendor/yiisoft/yii2/base/Application.php                                                                                           

It parser has problem when parsing mine `\CommonApplication` (code below) that required parsing `\yii2\base\Application`.

```
<?php
abstract class CommonApplication extends yii\base\Application
{
}
```

adding `\ ` after `extends` like `abstract class CommonApplication extends \yii\base\Application` solves the problem

i have parser-reflection@1.1.0

### PR DESCRIPTION
**Pull request by Fedott**
Fixes #42

### CODE REVIEW

**Comment by aik099** [comment]
Please also add a test case.

File: src/ReflectionEngine.php [hunk 1]
```diff
@@ -239,7 +239,7 @@ public static function parseFileNamespace($fileName, $namespaceName)
                 continue;
             }
             $topLevelNodeName = $topLevelNode->name ? $topLevelNode->name->toString() : '';
-            if ($topLevelNodeName === $namespaceName) {
+            if ($topLevelNodeName === $namespaceName || "\\{$topLevelNodeName}" === $namespaceName) {
```
Comment (lisachenko) [inline src/ReflectionEngine.php]: It will be better to normalize this value before any additional actions in the method beginning. Eg.

```php
$namespaceName = ltrim($namespaceName, '\\');
```

Then we will reduce method complexity by avoiding extra check in the if expression.

Comment (aik099) [inline src/ReflectionEngine.php]: Then we need to normalize both `$namespaceName` and `$topLevelNodeName` because both developer can supply `$namespaceName` with leading `\` and in analyzed PHP file namespace can be defined as `namespace \NamespaceExample;`.

**Comment by Fedott** [comment]
Hi!
I added test for specific case from issue #44 and added normalize for both namespace on compare.

**Comment by hijarian** [comment]
I suspect this PR fixes https://github.com/Codeception/AspectMock/issues/117 as well and supersedes my own PR https://github.com/goaop/parser-reflection/pull/66, would be great if you merge it.

**Comment by lisachenko** [comment]
Hi! Thanks!
